# Generated by Django 3.2.8 on 2022-11-05 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iotapi', '0003_vehicle_vehicletype_passenger_driver_assignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='conductor',
            new_name='driver',
        ),
    ]
