# Generated by Django 3.2.8 on 2022-11-05 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iotapi', '0004_rename_conductor_assignment_driver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='id_vehicle',
            new_name='number_vehicle',
        ),
    ]
