# Generated by Django 4.1.2 on 2022-11-09 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iotapi', '0005_rename_id_vehicle_vehicle_number_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='vehicle_type', to='iotapi.vehicletype'),
        ),
    ]
